set(BS_BANSHEEEDITOREXEC_INC_NOFILTER
	"resource.h"
)

set(BS_BANSHEEEDITOREXEC_SRC_NOFILTER
	"BsEditorExec.cpp"
)

source_group("Header Files" FILES ${BS_BANSHEEEDITOREXEC_INC_NOFILTER})
source_group("Source Files" FILES ${BS_BANSHEEEDITOREXEC_SRC_NOFILTER})

set(BS_BANSHEEEDITOREXEC_SRC
	${BS_BANSHEEEDITOREXEC_INC_NOFILTER}
	${BS_BANSHEEEDITOREXEC_SRC_NOFILTER}
)