find_path(FLAC_INCLUDE_DIR FLAC/all.h)
find_library(FLAC_LIBRARY FLAC)

set(FLAC_INCLUDE_DIRS ${FLAC_INCLUDE_DIR})
set(FLAC_LIBRARIES ${FLAC_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(FLAC REQUIRED_VARS FLAC_INCLUDE_DIR FLAC_LIBRARY)

if(FLAC_FOUND AND NOT TARGET FLAC::FLAC)
	add_library(FLAC::FLAC SHARED IMPORTED)
	set_target_properties(FLAC::FLAC PROPERTIES
		IMPORTED_LOCATION "${FLAC_LIBRARY}"
		INTERFACE_INCLUDE_DIRECTORIES "${FLAC_INCLUDE_DIRS}")
endif()
