set(BS_BANSHEEFREEIMGIMPORTER_INC_NOFILTER
	"BsFreeImgPrerequisites.h"
	"BsFreeImgImporter.h"
)

set(BS_BANSHEEFREEIMGIMPORTER_SRC_NOFILTER
	"BsFreeImgPlugin.cpp"
	"BsFreeImgImporter.cpp"
)

source_group("Header Files" FILES ${BS_BANSHEEFREEIMGIMPORTER_INC_NOFILTER})
source_group("Source Files" FILES ${BS_BANSHEEFREEIMGIMPORTER_SRC_NOFILTER})

set(BS_BANSHEEFREEIMGIMPORTER_SRC
	${BS_BANSHEEFREEIMGIMPORTER_INC_NOFILTER}
	${BS_BANSHEEFREEIMGIMPORTER_SRC_NOFILTER}
)