set(BS_EXAMPLELLR_INC_NOFILTER
)

set(BS_EXAMPLELLR_SRC_NOFILTER
	"Source/Main.cpp"
)

source_group("Header Files" FILES ${BS_EXAMPLELLR_INC_NOFILTER})
source_group("Source Files" FILES ${BS_EXAMPLELLR_SRC_NOFILTER})

set(BS_EXAMPLELLR_SRC
	${BS_EXAMPLELLR_INC_NOFILTER}
	${BS_EXAMPLELLR_SRC_NOFILTER}
)