set(BS_NULLRENDERER_INC_NOFILTER
	"BsNullRenderer.h"
	"BsNullRendererPrerequisites.h"
)

set(BS_NULLRENDERER_SRC_NOFILTER
	"BsNullRenderer.cpp"
	"BsNullRendererPlugin.cpp"
)

if(WIN32)
	set(BS_NULLRENDERER_WIN32RES
	"BsNullRendererWin32Resource.rc"
	)
else()
	set(BS_NULLRENDERER_WIN32RES )
endif()

source_group("" FILES ${BS_NULLRENDERER_INC_NOFILTER} ${BS_NULLRENDERER_SRC_NOFILTER} ${BS_NULLRENDERER_WIN32RES})

set(BS_NULLRENDERER_SRC
	${BS_NULLRENDERER_INC_NOFILTER}
	${BS_NULLRENDERER_SRC_NOFILTER}
	${BS_NULLRENDERER_WIN32RES}
)
