set(BS_FREEIMGIMPORTER_INC_NOFILTER
	"BsFreeImgPrerequisites.h"
	"BsFreeImgImporter.h"
)

set(BS_FREEIMGIMPORTER_SRC_NOFILTER
	"BsFreeImgPlugin.cpp"
	"BsFreeImgImporter.cpp"
)

source_group("" FILES ${BS_FREEIMGIMPORTER_SRC_NOFILTER} ${BS_FREEIMGIMPORTER_INC_NOFILTER})

set(BS_FREEIMGIMPORTER_SRC
	${BS_FREEIMGIMPORTER_INC_NOFILTER}
	${BS_FREEIMGIMPORTER_SRC_NOFILTER}
)