set(BS_FREEIMGIMPORTER_INC_NOFILTER
	"BsFreeImgPrerequisites.h"
	"BsFreeImgImporter.h"
)

set(BS_FREEIMGIMPORTER_SRC_NOFILTER
	"BsFreeImgPlugin.cpp"
	"BsFreeImgImporter.cpp"
)

if(WIN32)
	set(BS_FREEIMGIMPORTER_WIN32RES
	"BsFreeImgWin32Resource.rc"
	)
else()
	set(BS_FREEIMGIMPORTER_WIN32RES )
endif()

source_group("" FILES ${BS_FREEIMGIMPORTER_SRC_NOFILTER} ${BS_FREEIMGIMPORTER_INC_NOFILTER} ${BS_FREEIMGIMPORTER_WIN32RES})

set(BS_FREEIMGIMPORTER_SRC
	${BS_FREEIMGIMPORTER_INC_NOFILTER}
	${BS_FREEIMGIMPORTER_SRC_NOFILTER}
	${BS_FREEIMGIMPORTER_WIN32RES}
)
