set(BS_BANSHEEFMOD_INC_NOFILTER
	""
)

set(BS_BANSHEEFMOD_SRC_NOFILTER
	""
)

source_group("Header Files" FILES ${BS_BANSHEEFMOD_INC_NOFILTER})
source_group("Source Files" FILES ${BS_BANSHEEFMOD_SRC_NOFILTER})

set(BS_BANSHEEOPENAUDIO_SRC
	${BS_BANSHEEFMOD_INC_NOFILTER}
	${BS_BANSHEEFMOD_SRC_NOFILTER}
)