set(BS_FBXIMPORTER_INC_NOFILTER
	"BsFBXPrerequisites.h"
	"BsFBXImporter.h"
	"BsFBXImportData.h"
	"BsFBXUtility.h"
)

set(BS_FBXIMPORTER_SRC_NOFILTER
	"BsFBXPlugin.cpp"
	"BsFBXImporter.cpp"
	"BsFBXUtility.cpp"
	"BsFBXImportData.cpp"
)

if(WIN32)
	set(BS_FBXIMPORTER_WIN32RES
	"BsFBXWin32Resource.rc"
	)
else()
	set(BS_FBXIMPORTER_WIN32RES )
endif()

source_group("" FILES ${BS_FBXIMPORTER_INC_NOFILTER} ${BS_FBXIMPORTER_SRC_NOFILTER} ${BS_FBXIMPORTER_WIN32RES})

set(BS_FBXIMPORTER_SRC
	${BS_FBXIMPORTER_INC_NOFILTER}
	${BS_FBXIMPORTER_SRC_NOFILTER}
	${BS_FBXIMPORTER_WIN32RES}
)
