set(BS_SBANSHEEENGINE_INC_NOFILTER
	"BsScriptObject.h"
	"BsScriptEnginePrerequisites.h"
	"BsManagedComponent.h"
	"BsScriptResourceManager.h"
	"BsScriptGameObjectManager.h"
	"BsScriptObjectImpl.h"
	"BsManagedResource.h"
	"BsManagedResourceMetaData.h"
	"BsManagedResourceManager.h"
	"BsScriptObjectManager.h"
	"BsScriptStringTableManager.h"
	"BsEngineScriptLibrary.h"
	"BsPlayInEditorManager.h"
)

set(BS_SBANSHEEENGINE_SRC_WRAPPERS_GUI
	"Wrappers/GUI/BsScriptRange.cpp"
	"Wrappers/GUI/BsScriptStep.cpp"
	"Wrappers/GUI/BsScriptGUIButton.cpp"
	"Wrappers/GUI/BsScriptGUIContent.cpp"
	"Wrappers/GUI/BsScriptGUIElementStateStyle.cpp"
	"Wrappers/GUI/BsScriptGUIElementStyle.cpp"
	"Wrappers/GUI/BsScriptGUIFixedSpace.cpp"
	"Wrappers/GUI/BsScriptGUIFlexibleSpace.cpp"
	"Wrappers/GUI/BsScriptGUIInputBox.cpp"
	"Wrappers/GUI/BsScriptGUILabel.cpp"
	"Wrappers/GUI/BsScriptGUILayout.cpp"
	"Wrappers/GUI/BsScriptGUIListBox.cpp"
	"Wrappers/GUI/BsScriptGUIScrollArea.cpp"
	"Wrappers/GUI/BsScriptGUITexture.cpp"
	"Wrappers/GUI/BsScriptGUIToggle.cpp"
	"Wrappers/GUI/BsScriptGUIToggleGroup.cpp"
	"Wrappers/GUI/BsScriptGUIElement.cpp"
	"Wrappers/GUI/BsScriptGUIUtility.cpp"
	"Wrappers/GUI/BsScriptGUIRenderTexture.cpp"
	"Wrappers/GUI/BsScriptGUISlider.cpp"
	"Wrappers/GUI/BsScriptGUIProgressBar.cpp"
	"Wrappers/GUI/BsScriptGUISkin.cpp"
	"Wrappers/GUI/BsScriptGUIWidget.cpp"
	"Wrappers/GUI/BsScriptGUI.cpp"
	"Wrappers/GUI/BsScriptGUICanvas.cpp"
	"Wrappers/GUI/BsScriptGUIScrollBar.cpp"
)

set(BS_SBANSHEEENGINE_INC_SERIALIZATION_RTTI
	"RTTI/BsManagedSerializableArrayRTTI.h"
	"RTTI/BsManagedSerializableDictionaryRTTI.h"
	"RTTI/BsManagedSerializableListRTTI.h"
	"RTTI/BsManagedSerializableObjectRTTI.h"
	"RTTI/BsManagedSerializableFieldRTTI.h"
	"RTTI/BsManagedSerializableObjectInfoRTTI.h"
	"RTTI/BsManagedSerializableDiffRTTI.h"
)

set(BS_SBANSHEEENGINE_SRC_WRAPPERS_PHYSICS
	"Wrappers/Physics/BsScriptCollider.cpp"
	"Wrappers/Physics/BsScriptCollisionData.cpp"
	"Wrappers/Physics/BsScriptPhysicsQueryHit.cpp"
	"Wrappers/Physics/BsScriptRigidbody.cpp"
	"Wrappers/Physics/BsScriptBoxCollider.cpp"
	"Wrappers/Physics/BsScriptSphereCollider.cpp"
	"Wrappers/Physics/BsScriptCapsuleCollider.cpp"
	"Wrappers/Physics/BsScriptPlaneCollider.cpp"
	"Wrappers/Physics/BsScriptMeshCollider.cpp"
	"Wrappers/Physics/BsScriptJointCommon.cpp"
	"Wrappers/Physics/BsScriptControllerCollision.cpp"
	"Wrappers/Physics/BsScriptCharacterController.cpp"
	"Wrappers/Physics/BsScriptJoint.cpp"
	"Wrappers/Physics/BsScriptDistanceJoint.cpp"
	"Wrappers/Physics/BsScriptHingeJoint.cpp"
	"Wrappers/Physics/BsScriptSliderJoint.cpp"
	"Wrappers/Physics/BsScriptFixedJoint.cpp"
	"Wrappers/Physics/BsScriptSphericalJoint.cpp"
	"Wrappers/Physics/BsScriptD6Joint.cpp"
	"Wrappers/Physics/BsScriptPhysics.cpp"
)

set(BS_SBANSHEEENGINE_INC_WRAPPERS
	"Wrappers/BsScriptBuiltin.h"
	"Wrappers/BsScriptCamera.h"
	"Wrappers/BsScriptColor.h"
	"Wrappers/BsScriptComponent.h"
	"Wrappers/BsScriptContextMenu.h"
	"Wrappers/BsScriptCursor.h"
	"Wrappers/BsScriptDebug.h"
	"Wrappers/BsScriptFont.h"
	"Wrappers/BsScriptFontBitmap.h"
	"Wrappers/BsScriptGameObject.h"
	"Wrappers/BsScriptGUIContentImages.h"
	"Wrappers/BsScriptHString.h"
	"Wrappers/BsScriptInput.h"
	"Wrappers/BsScriptInputConfiguration.h"
	"Wrappers/BsScriptLight.h"
	"Wrappers/BsScriptLogEntry.h"
	"Wrappers/BsScriptManagedResource.h"
	"Wrappers/BsScriptMaterial.h"
	"Wrappers/BsScriptPixelUtility.h"
	"Wrappers/BsScriptPlainText.h"
	"Wrappers/BsScriptPrefab.h"
	"Wrappers/BsScriptProfilerOverlayInternal.h"
	"Wrappers/BsScriptRenderable.h"
	"Wrappers/BsScriptRenderTarget.h"
	"Wrappers/BsScriptRenderTexture.h"
	"Wrappers/BsScriptRenderTexture2D.h"
	"Wrappers/BsScriptResource.h"
	"Wrappers/BsScriptVirtualInput.h"
	"Wrappers/BsScriptVirtualButton.h"
	"Wrappers/BsScriptVector2I.h"
	"Wrappers/BsScriptVector.h"
	"Wrappers/BsScriptTime.h"
	"Wrappers/BsScriptStringTable.h"
	"Wrappers/BsScriptSpriteTexture.h"
	"Wrappers/BsScriptShaderInclude.h"
	"Wrappers/BsScriptShader.h"
	"Wrappers/BsScriptSerializableUtility.h"
	"Wrappers/BsScriptSerializableProperty.h"
	"Wrappers/BsScriptSerializableObject.h"
	"Wrappers/BsScriptSerializableList.h"
	"Wrappers/BsScriptSerializableField.h"
	"Wrappers/BsScriptSerializableDictionary.h"
	"Wrappers/BsScriptScriptCode.h"
	"Wrappers/BsScriptSerializableArray.h"
	"Wrappers/BsScriptSceneObject.h"
	"Wrappers/BsScriptScene.h"
	"Wrappers/BsScriptResources.h"
	"Wrappers/BsScriptResourceRef.h"
	"Wrappers/BsScriptRenderSettings.h"
	"Wrappers/BsScriptAnimation.h"
	"Wrappers/BsScriptManagedComponent.h"
	"Wrappers/BsScriptQuaternion.h"
)

set(BS_SBANSHEEENGINE_INC_WRAPPERS_GUI
	"Wrappers/GUI/BsScriptRange.h"
	"Wrappers/GUI/BsScriptStep.h"
	"Wrappers/GUI/BsScriptGUIButton.h"
	"Wrappers/GUI/BsScriptGUIContent.h"
	"Wrappers/GUI/BsScriptGUIElementStateStyle.h"
	"Wrappers/GUI/BsScriptGUIElementStyle.h"
	"Wrappers/GUI/BsScriptGUIFixedSpace.h"
	"Wrappers/GUI/BsScriptGUIFlexibleSpace.h"
	"Wrappers/GUI/BsScriptGUIInputBox.h"
	"Wrappers/GUI/BsScriptGUILabel.h"
	"Wrappers/GUI/BsScriptGUILayout.h"
	"Wrappers/GUI/BsScriptGUIListBox.h"
	"Wrappers/GUI/BsScriptGUIScrollArea.h"
	"Wrappers/GUI/BsScriptGUITexture.h"
	"Wrappers/GUI/BsScriptGUIToggle.h"
	"Wrappers/GUI/BsScriptGUIToggleGroup.h"
	"Wrappers/GUI/BsScriptGUIElement.h"
	"Wrappers/GUI/BsScriptGUIUtility.h"
	"Wrappers/GUI/BsScriptGUIRenderTexture.h"
	"Wrappers/GUI/BsScriptGUISlider.h"
	"Wrappers/GUI/BsScriptGUIProgressBar.h"
	"Wrappers/GUI/BsScriptGUISkin.h"
	"Wrappers/GUI/BsScriptGUIWidget.h"
	"Wrappers/GUI/BsScriptGUI.h"
	"Wrappers/GUI/BsScriptGUICanvas.h"
	"Wrappers/GUI/BsScriptGUIScrollBar.h"
)

set(BS_SBANSHEEENGINE_INC_WRAPPERS_PHYSICS
	"Wrappers/Physics/BsScriptCollider.h"
	"Wrappers/Physics/BsScriptCollisionData.h"
	"Wrappers/Physics/BsScriptPhysicsQueryHit.h"
	"Wrappers/Physics/BsScriptRigidbody.h"
	"Wrappers/Physics/BsScriptBoxCollider.h"
	"Wrappers/Physics/BsScriptSphereCollider.h"
	"Wrappers/Physics/BsScriptCapsuleCollider.h"
	"Wrappers/Physics/BsScriptPlaneCollider.h"
	"Wrappers/Physics/BsScriptMeshCollider.h"
	"Wrappers/Physics/BsScriptJointCommon.h"
	"Wrappers/Physics/BsScriptControllerCollision.h"
	"Wrappers/Physics/BsScriptCharacterController.h"
	"Wrappers/Physics/BsScriptJoint.h"
	"Wrappers/Physics/BsScriptDistanceJoint.h"
	"Wrappers/Physics/BsScriptHingeJoint.h"
	"Wrappers/Physics/BsScriptSliderJoint.h"
	"Wrappers/Physics/BsScriptSphericalJoint.h"
	"Wrappers/Physics/BsScriptFixedJoint.h"
	"Wrappers/Physics/BsScriptD6Joint.h"
	"Wrappers/Physics/BsScriptPhysics.h"
)

set(BS_SBANSHEEENGINE_SRC_SERIALIZATION
	"Serialization/BsManagedSerializableArray.cpp"
	"Serialization/BsManagedSerializableDictionary.cpp"
	"Serialization/BsManagedSerializableField.cpp"
	"Serialization/BsManagedSerializableList.cpp"
	"Serialization/BsManagedSerializableObject.cpp"
	"Serialization/BsManagedSerializableObjectInfo.cpp"
	"Serialization/BsScriptAssemblyManager.cpp"
	"Serialization/BsManagedSerializableDiff.cpp"
	"Serialization/BsManagedDiff.cpp"
)

set(BS_SBANSHEEENGINE_SRC_WRAPPERS
	"Wrappers/BsScriptBuiltin.cpp"
	"Wrappers/BsScriptCamera.cpp"
	"Wrappers/BsScriptColor.cpp"
	"Wrappers/BsScriptComponent.cpp"
	"Wrappers/BsScriptContextMenu.cpp"
	"Wrappers/BsScriptCursor.cpp"
	"Wrappers/BsScriptDebug.cpp"
	"Wrappers/BsScriptFont.cpp"
	"Wrappers/BsScriptFontBitmap.cpp"
	"Wrappers/BsScriptGameObject.cpp"
	"Wrappers/BsScriptGUIContentImages.cpp"
	"Wrappers/BsScriptHString.cpp"
	"Wrappers/BsScriptInput.cpp"
	"Wrappers/BsScriptInputConfiguration.cpp"
	"Wrappers/BsScriptLight.cpp"
	"Wrappers/BsScriptLogEntry.cpp"
	"Wrappers/BsScriptManagedResource.cpp"
	"Wrappers/BsScriptMaterial.cpp"
	"Wrappers/BsScriptPixelUtility.cpp"
	"Wrappers/BsScriptPlainText.cpp"
	"Wrappers/BsScriptPrefab.cpp"
	"Wrappers/BsScriptProfilerOverlayInternal.cpp"
	"Wrappers/BsScriptVirtualInput.cpp"
	"Wrappers/BsScriptVirtualButton.cpp"
	"Wrappers/BsScriptVector2I.cpp"
	"Wrappers/BsScriptVector.cpp"
	"Wrappers/BsScriptTime.cpp"
	"Wrappers/BsScriptStringTable.cpp"
	"Wrappers/BsScriptSpriteTexture.cpp"
	"Wrappers/BsScriptShaderInclude.cpp"
	"Wrappers/BsScriptShader.cpp"
	"Wrappers/BsScriptSerializableUtility.cpp"
	"Wrappers/BsScriptSerializableProperty.cpp"
	"Wrappers/BsScriptSerializableObject.cpp"
	"Wrappers/BsScriptSerializableList.cpp"
	"Wrappers/BsScriptSerializableField.cpp"
	"Wrappers/BsScriptSerializableDictionary.cpp"
	"Wrappers/BsScriptSerializableArray.cpp"
	"Wrappers/BsScriptScriptCode.cpp"
	"Wrappers/BsScriptSceneObject.cpp"
	"Wrappers/BsScriptScene.cpp"
	"Wrappers/BsScriptResources.cpp"
	"Wrappers/BsScriptResourceRef.cpp"
	"Wrappers/BsScriptResource.cpp"
	"Wrappers/BsScriptRenderTexture2D.cpp"
	"Wrappers/BsScriptRenderTexture.cpp"
	"Wrappers/BsScriptRenderTarget.cpp"
	"Wrappers/BsScriptRenderable.cpp"
	"Wrappers/BsScriptRenderSettings.cpp"
	"Wrappers/BsScriptAnimation.cpp"
	"Wrappers/BsScriptManagedComponent.cpp"
	"Wrappers/BsScriptQuaternion.cpp"
)

set(BS_SBANSHEEENGINE_INC_SERIALIZATION
	"Serialization/BsManagedSerializableArray.h"
	"Serialization/BsManagedSerializableDictionary.h"
	"Serialization/BsManagedSerializableList.h"
	"Serialization/BsManagedSerializableObject.h"
	"Serialization/BsManagedSerializableField.h"
	"Serialization/BsManagedSerializableObjectInfo.h"
	"Serialization/BsScriptAssemblyManager.h"
	"Serialization/BsManagedSerializableDiff.h"
	"Serialization/BsManagedDiff.h"
	"Serialization/BsBuiltinComponentLookup.h"
	"Serialization/BsBuiltinResourceLookup.h"
)

set(BS_SBANSHEEENGINE_SRC_NOFILTER
	"BsScriptEnginePlugin.cpp"
	"BsManagedComponent.cpp"
	"BsScriptResourceManager.cpp"
	"BsScriptGameObjectManager.cpp"
	"BsScriptObjectImpl.cpp"
	"BsScriptObject.cpp"
	"BsManagedResource.cpp"
	"BsManagedResourceMetaData.cpp"
	"BsManagedResourceManager.cpp"
	"BsScriptObjectManager.cpp"
	"BsScriptStringTableManager.cpp"
	"BsEngineScriptLibrary.cpp"
	"BsPlayInEditorManager.cpp"
)

set(BS_SBANSHEEENGINE_INC_RTTI
	"RTTI/BsManagedComponentRTTI.h"
	"RTTI/BsManagedResourceRTTI.h"
	"RTTI/BsManagedResourceMetaDataRTTI.h"
)

set(BS_SBANSHEEENGINE_INC_EXTENSIONS
	"Extensions/BsPixelDataEx.h"
	"Extensions/BsAsyncOpEx.h"
	"Extensions/BsTextureEx.h"
	"Extensions/BsMeshDataEx.h"
	"Extensions/BsMeshEx.h"
	"Extensions/BsSkeletonEx.h"
	"Extensions/BsPhysicsMeshEx.h"
	"Extensions/BsAnimationEx.h"
)

set(BS_SBANSHEEENGINE_SRC_EXTENSIONS
	"Extensions/BsPixelDataEx.cpp"
	"Extensions/BsAsyncOpEx.cpp"
	"Extensions/BsTextureEx.cpp"
	"Extensions/BsMeshDataEx.cpp"
	"Extensions/BsMeshEx.cpp"
	"Extensions/BsSkeletonEx.cpp"
	"Extensions/BsPhysicsMeshEx.cpp"
	"Extensions/BsAnimationEx.cpp"
)

source_group("Header Files" FILES ${BS_SBANSHEEENGINE_INC_NOFILTER})
source_group("Source Files\\Wrappers\\GUI" FILES ${BS_SBANSHEEENGINE_SRC_WRAPPERS_GUI})
source_group("Header Files\\Serialization\\RTTI" FILES ${BS_SBANSHEEENGINE_INC_SERIALIZATION_RTTI})
source_group("Source Files\\Wrappers\\Physics" FILES ${BS_SBANSHEEENGINE_SRC_WRAPPERS_PHYSICS})
source_group("Header Files\\Wrappers" FILES ${BS_SBANSHEEENGINE_INC_WRAPPERS})
source_group("Header Files\\Wrappers\\GUI" FILES ${BS_SBANSHEEENGINE_INC_WRAPPERS_GUI})
source_group("Header Files\\Wrappers\\Physics" FILES ${BS_SBANSHEEENGINE_INC_WRAPPERS_PHYSICS})
source_group("Source Files\\Serialization" FILES ${BS_SBANSHEEENGINE_SRC_SERIALIZATION})
source_group("Source Files\\Wrappers" FILES ${BS_SBANSHEEENGINE_SRC_WRAPPERS})
source_group("Header Files\\Serialization" FILES ${BS_SBANSHEEENGINE_INC_SERIALIZATION})
source_group("Source Files" FILES ${BS_SBANSHEEENGINE_SRC_NOFILTER})
source_group("Header Files\\RTTI" FILES ${BS_SBANSHEEENGINE_INC_RTTI})
source_group("Header Files\\Extensions" FILES ${BS_SBANSHEEENGINE_INC_EXTENSIONS})
source_group("Source Files\\Extensions" FILES ${BS_SBANSHEEENGINE_SRC_EXTENSIONS})

set(BS_SBANSHEEENGINE_SRC
	${BS_SBANSHEEENGINE_INC_NOFILTER}
	${BS_SBANSHEEENGINE_SRC_WRAPPERS_GUI}
	${BS_SBANSHEEENGINE_INC_SERIALIZATION_RTTI}
	${BS_SBANSHEEENGINE_SRC_WRAPPERS_PHYSICS}
	${BS_SBANSHEEENGINE_INC_WRAPPERS}
	${BS_SBANSHEEENGINE_INC_WRAPPERS_GUI}
	${BS_SBANSHEEENGINE_INC_WRAPPERS_PHYSICS}
	${BS_SBANSHEEENGINE_SRC_SERIALIZATION}
	${BS_SBANSHEEENGINE_SRC_WRAPPERS}
	${BS_SBANSHEEENGINE_INC_SERIALIZATION}
	${BS_SBANSHEEENGINE_SRC_NOFILTER}
	${BS_SBANSHEEENGINE_INC_RTTI}
	${BS_SBANSHEEENGINE_INC_EXTENSIONS}
	${BS_SBANSHEEENGINE_SRC_EXTENSIONS}
)