set(BS_FONTIMPORTER_INC_NOFILTER
	"BsFontPrerequisites.h"
	"BsFontImporter.h"
)

set(BS_FONTIMPORTER_SRC_NOFILTER
	"BsFontPlugin.cpp"
	"BsFontImporter.cpp"
)

if(WIN32)
	set(BS_FONTIMPORTER_WIN32RES
	"BsFontWin32Resource.rc"
	)
else()
	set(BS_FONTIMPORTER_WIN32RES )
endif()

source_group("" FILES ${BS_FONTIMPORTER_INC_NOFILTER} ${BS_FONTIMPORTER_SRC_NOFILTER} ${BS_FONTIMPORTER_WIN32RES})

set(BS_FONTIMPORTER_SRC
	${BS_FONTIMPORTER_INC_NOFILTER}
	${BS_FONTIMPORTER_SRC_NOFILTER}
	${BS_FONTIMPORTER_WIN32RES}
)
