set(BS_FONTIMPORTER_INC_NOFILTER
	"BsFontPrerequisites.h"
	"BsFontImporter.h"
)

set(BS_FONTIMPORTER_SRC_NOFILTER
	"BsFontPlugin.cpp"
	"BsFontImporter.cpp"
)

source_group("" FILES ${BS_FONTIMPORTER_INC_NOFILTER} ${BS_FONTIMPORTER_SRC_NOFILTER})

set(BS_FONTIMPORTER_SRC
	${BS_FONTIMPORTER_INC_NOFILTER}
	${BS_FONTIMPORTER_SRC_NOFILTER}
)