set(BS_ECSRENDERER_INC_NOFILTER
	"BsECSRenderer.h"
	"BsECSRendererPrerequisites.h"
)

set(BS_ECSRENDERER_SRC_NOFILTER
	"BsECSRenderer.cpp"
	"BsECSRendererPlugin.cpp"
)

if(WIN32)
	set(BS_ECSRENDERER_WIN32RES
	"BsECSRendererWin32Resource.rc"
	)
else()
	set(BS_ECSRENDERER_WIN32RES )
endif()

source_group("" FILES
	${BS_ECSRENDERER_INC_NOFILTER}
	${BS_ECSRENDERER_SRC_NOFILTER}
	${BS_ECSRENDERER_WIN32RES})

set(BS_ECSRENDERER_SRC
	${BS_ECSRENDERER_INC_NOFILTER}
	${BS_ECSRENDERER_SRC_NOFILTER}
	${BS_ECSRENDERER_WIN32RES}
)