set(BS_SBANSHEEEDITOR_INC_NOFILTER
	"BsScriptEditorPrerequisites.h"
	"BsGUIGameObjectField.h"
	"BsGUIResourceField.h"
	"BsEditorScriptManager.h"
	"BsScriptHandleManager.h"
	"BsScriptDragDropManager.h"
	"BsMenuItemManager.h"
	"BsGUITextureField.h"
	"BsEditorResourceLoader.h"
	"BsEditorScriptLibrary.h"
	"BsToolbarItemManager.h"
	"BsScriptGizmoManager.h"
	"BsManagedEditorCommand.h"
)

set(BS_SBANSHEEEDITOR_SRC_WRAPPERS_GUI
	"Wrappers/GUI/BsScriptGUIColorField.cpp"
	"Wrappers/GUI/BsScriptGUIEnumField.cpp"
	"Wrappers/GUI/BsScriptGUIFloatField.cpp"
	"Wrappers/GUI/BsScriptGUIGameObjectField.cpp"
	"Wrappers/GUI/BsScriptGUIIntField.cpp"
	"Wrappers/GUI/BsScriptGUIListBoxField.cpp"
	"Wrappers/GUI/BsScriptGUIResourceField.cpp"
	"Wrappers/GUI/BsScriptGUISceneTreeView.cpp"
	"Wrappers/GUI/BsScriptGUISliderField.cpp"
	"Wrappers/GUI/BsScriptGUITextField.cpp"
	"Wrappers/GUI/BsScriptGUITextureField.cpp"
	"Wrappers/GUI/BsScriptGUIToggleField.cpp"
	"Wrappers/GUI/BsScriptGUIVector2Field.cpp"
	"Wrappers/GUI/BsScriptGUIVector3Field.cpp"
	"Wrappers/GUI/BsScriptGUIVector4Field.cpp"
)

set(BS_SBANSHEEEDITOR_SRC_WRAPPERS
	"Wrappers/BsScriptBrowseDialog.cpp"
	"Wrappers/BsScriptBuildManager.cpp"
	"Wrappers/BsScriptCodeEditor.cpp"
	"Wrappers/BsScriptDragDropManager.cpp"
	"Wrappers/BsScriptDropDownWindow.cpp"
	"Wrappers/BsScriptEditorApplication.cpp"
	"Wrappers/BsScriptEditorBuiltin.cpp"
	"Wrappers/BsScriptEditorInput.cpp"
	"Wrappers/BsScriptEditorSettings.cpp"
	"Wrappers/BsScriptEditorTestSuite.cpp"
	"Wrappers/BsScriptEditorUtility.cpp"
	"Wrappers/BsScriptEditorVirtualInput.cpp"
	"Wrappers/BsScriptEditorWindow.cpp"
	"Wrappers/BsScriptFolderMonitor.cpp"
	"Wrappers/BsScriptGizmos.cpp"
	"Wrappers/BsScriptHandleDrawing.cpp"
	"Wrappers/BsScriptHandleSlider.cpp"
	"Wrappers/BsScriptHandleSliderDisc.cpp"
	"Wrappers/BsScriptHandleSliderLine.cpp"
	"Wrappers/BsScriptHandleSliderManager.cpp"
	"Wrappers/BsScriptHandleSliderPlane.cpp"
	"Wrappers/BsScriptHandleSliderSphere.cpp"
	"Wrappers/BsScriptHandleSlider2D.cpp"
	"Wrappers/BsScriptImportOptions.cpp"
	"Wrappers/BsScriptInspectorUtility.cpp"
	"Wrappers/BsScriptModalWindow.cpp"
	"Wrappers/BsScriptOSDropTarget.cpp"
	"Wrappers/BsScriptPlatformInfo.cpp"
	"Wrappers/BsScriptPrefabUtility.cpp"
	"Wrappers/BsScriptProjectLibrary.cpp"
	"Wrappers/BsScriptProjectSettings.cpp"
	"Wrappers/BsScriptSceneGizmos.cpp"
	"Wrappers/BsScriptSceneGrid.cpp"
	"Wrappers/BsScriptSceneHandles.cpp"
	"Wrappers/BsScriptSceneSelection.cpp"
	"Wrappers/BsScriptSelection.cpp"
	"Wrappers/BsScriptUndoRedo.cpp"
	"Wrappers/BsScriptUnitTests.cpp"
	"Wrappers/BsScriptSerializedObject.cpp"
	"Wrappers/BsScriptSerializedDiff.cpp"
	"Wrappers/BsScriptSerializedSceneObject.cpp"
)

set(BS_SBANSHEEEDITOR_SRC_NOFILTER
	"BsScriptEditorPlugin.cpp"
	"BsGUIGameObjectField.cpp"
	"BsGUIResourceField.cpp"
	"BsEditorScriptManager.cpp"
	"BsScriptGizmoManager.cpp"
	"BsScriptHandleManager.cpp"
	"BsMenuItemManager.cpp"
	"BsGUITextureField.cpp"
	"BsEditorResourceLoader.cpp"
	"BsEditorScriptLibrary.cpp"
	"BsToolbarItemManager.cpp"
	"BsManagedEditorCommand.cpp"
)

set(BS_SBANSHEEEDITOR_INC_WRAPPERS
	"Wrappers/BsScriptCodeEditor.h"
	"Wrappers/BsScriptBrowseDialog.h"
	"Wrappers/BsScriptBuildManager.h"
	"Wrappers/BsScriptDropDownWindow.h"
	"Wrappers/BsScriptEditorApplication.h"
	"Wrappers/BsScriptEditorBuiltin.h"
	"Wrappers/BsScriptEditorInput.h"
	"Wrappers/BsScriptEditorSettings.h"
	"Wrappers/BsScriptEditorTestSuite.h"
	"Wrappers/BsScriptEditorUtility.h"
	"Wrappers/BsScriptEditorVirtualInput.h"
	"Wrappers/BsScriptEditorWindow.h"
	"Wrappers/BsScriptFolderMonitor.h"
	"Wrappers/BsScriptGizmos.h"
	"Wrappers/BsScriptUnitTests.h"
	"Wrappers/BsScriptUndoRedo.h"
	"Wrappers/BsScriptSelection.h"
	"Wrappers/BsScriptSceneSelection.h"
	"Wrappers/BsScriptSceneHandles.h"
	"Wrappers/BsScriptSceneGrid.h"
	"Wrappers/BsScriptSceneGizmos.h"
	"Wrappers/BsScriptProjectSettings.h"
	"Wrappers/BsScriptProjectLibrary.h"
	"Wrappers/BsScriptPrefabUtility.h"
	"Wrappers/BsScriptPlatformInfo.h"
	"Wrappers/BsScriptOSDropTarget.h"
	"Wrappers/BsScriptModalWindow.h"
	"Wrappers/BsScriptInspectorUtility.h"
	"Wrappers/BsScriptImportOptions.h"
	"Wrappers/BsScriptHandleSliderPlane.h"
	"Wrappers/BsScriptHandleSliderManager.h"
	"Wrappers/BsScriptHandleSliderLine.h"
	"Wrappers/BsScriptHandleSliderDisc.h"
	"Wrappers/BsScriptHandleSliderSphere.h"
	"Wrappers/BsScriptHandleSlider2D.h"
	"Wrappers/BsScriptHandleSlider.h"
	"Wrappers/BsScriptHandleDrawing.h"
	"Wrappers/BsScriptSerializedObject.h"
	"Wrappers/BsScriptSerializedDiff.h"	
	"Wrappers/BsScriptSerializedSceneObject.h"
)

set(BS_SBANSHEEEDITOR_INC_WRAPPERS_GUI
	"Wrappers/GUI/BsScriptGUIColorField.h"
	"Wrappers/GUI/BsScriptGUIEnumField.h"
	"Wrappers/GUI/BsScriptGUIFloatField.h"
	"Wrappers/GUI/BsScriptGUIGameObjectField.h"
	"Wrappers/GUI/BsScriptGUIIntField.h"
	"Wrappers/GUI/BsScriptGUIListBoxField.h"
	"Wrappers/GUI/BsScriptGUIResourceField.h"
	"Wrappers/GUI/BsScriptGUISceneTreeView.h"
	"Wrappers/GUI/BsScriptGUISliderField.h"
	"Wrappers/GUI/BsScriptGUITextField.h"
	"Wrappers/GUI/BsScriptGUITextureField.h"
	"Wrappers/GUI/BsScriptGUIToggleField.h"
	"Wrappers/GUI/BsScriptGUIVector2Field.h"
	"Wrappers/GUI/BsScriptGUIVector3Field.h"
	"Wrappers/GUI/BsScriptGUIVector4Field.h"
)

source_group("Header Files" FILES ${BS_SBANSHEEEDITOR_INC_NOFILTER})
source_group("Source Files\\Wrappers\\GUI" FILES ${BS_SBANSHEEEDITOR_SRC_WRAPPERS_GUI})
source_group("Source Files\\Wrappers" FILES ${BS_SBANSHEEEDITOR_SRC_WRAPPERS})
source_group("Source Files" FILES ${BS_SBANSHEEEDITOR_SRC_NOFILTER})
source_group("Header Files\\Wrappers" FILES ${BS_SBANSHEEEDITOR_INC_WRAPPERS})
source_group("Header Files\\Wrappers\\GUI" FILES ${BS_SBANSHEEEDITOR_INC_WRAPPERS_GUI})

set(BS_SBANSHEEEDITOR_SRC
	${BS_SBANSHEEEDITOR_INC_NOFILTER}
	${BS_SBANSHEEEDITOR_SRC_WRAPPERS_GUI}
	${BS_SBANSHEEEDITOR_SRC_WRAPPERS}
	${BS_SBANSHEEEDITOR_SRC_NOFILTER}
	${BS_SBANSHEEEDITOR_INC_WRAPPERS}
	${BS_SBANSHEEEDITOR_INC_WRAPPERS_GUI}
)