
#line 3 "BsLexerFX.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart (FILE *input_file ,yyscan_t yyscanner );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void yy_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yy_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void yypop_buffer_state (yyscan_t yyscanner );

static void yyensure_buffer_stack (yyscan_t yyscanner );
static void yy_load_buffer_state (yyscan_t yyscanner );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len ,yyscan_t yyscanner );

void *yyalloc (yy_size_t ,yyscan_t yyscanner );
void *yyrealloc (void *,yy_size_t ,yyscan_t yyscanner );
void yyfree (void * ,yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(yyscanner) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 162
#define YY_END_OF_BUFFER 163
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[535] =
    {   0,
        1,    1,  106,  106,  148,  148,    0,    0,  158,  158,
        0,    0,  114,  114,  117,  117,  121,  121,  125,  125,
      129,  129,  143,  143,  135,  135,  163,  161,    1,    1,
      161,  161,  161,  161,    2,    2,   93,   92,  160,   91,
       90,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  108,  106,  106,  108,  149,  148,  148,  147,  152,
      152,  150,  151,  158,  158,  153,  154,  155,  156,  157,
      113,  110,  112,  112,  111,  114,  115,  119,  117,  117,
      118,  123,  121,  121,  122,  127,  125,  125,  126,  131,

      129,  129,  130,  145,  143,  143,  144,  142,  135,  135,
      142,    1,    0,    5,    0,    0,    0,    0,    2,  159,
        0,    2,    0,  160,   99,   98,   97,   96,   95,   94,
      160,  160,  160,  160,  160,  160,  160,  160,  160,   55,
      160,  160,  160,  160,  160,   63,  160,  160,  160,  160,
       66,  160,  160,  160,   61,  160,  160,  160,  160,  160,
      160,   51,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  106,    0,  107,  148,  158,  111,  114,  117,  118,
      121,  122,  125,  126,  129,  130,  143,  144,  135,    0,

        0,    0,    0,    0,  120,    0,    0,    2,  159,    4,
        3,  103,  102,  101,  100,   84,  160,  160,  160,  160,
      160,   56,  160,  160,  160,  160,  160,   71,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,   65,
       70,  160,  160,  160,  160,   62,   88,   87,  160,  160,
       64,  160,  160,   75,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
       85,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,    0,    0,  136,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    4,  104,  160,  160,   40,   32,  160,

       34,  146,  160,  160,   25,  160,  160,   50,  160,   80,
      160,  160,  160,  160,   41,  160,  160,   24,  160,  160,
      160,  160,   67,  160,  160,  160,  160,   54,  160,   17,
      160,  160,   29,  160,  160,   86,  160,  160,  160,  160,
       12,  160,   81,  160,  160,  160,   16,  160,  160,  160,
        6,  160,   52,  160,   68,  160,    0,    0,    0,    0,
        0,    0,  133,  132,    0,    0,    0,    0,    0,    0,
        4,   48,  160,  160,   19,   47,  160,  160,   21,  160,
       82,  160,  160,   89,  160,    7,  160,   39,  160,  160,
       46,  160,  160,   10,  160,   59,  160,  160,  160,  160,

      160,  160,  160,  160,  160,   53,  160,   83,  160,  160,
      160,  160,  160,  160,  160,   30,   42,  140,  139,    0,
        0,    0,    0,  134,  124,    0,    0,  116,   60,  160,
      160,  160,   43,  160,   76,  160,  160,  160,  160,  160,
      160,   28,  160,  160,  160,   20,  160,  160,  160,  160,
      160,  160,   49,  160,   77,  160,   45,  160,  160,  160,
      160,  141,  137,    0,  109,  128,    0,  160,   31,   73,
       78,   36,  160,  160,   72,  160,   74,  160,    8,  160,
      160,  160,   69,  160,   26,  160,   79,   22,  160,  160,
      160,  160,  138,  105,  160,  160,  160,  160,  160,   13,

       37,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,   35,  160,   11,    9,  160,   23,   38,
      160,   15,  160,  160,  160,   33,  160,   18,   58,   57,
       44,   27,   14,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    1,    1,    1,    1,
        1,    1,    7,    1,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   16,   16,   16,   16,    1,    1,    1,
        1,    1,    1,    1,   17,   18,   19,   19,   20,   21,
       22,   23,   24,   23,   23,   23,   23,   23,   23,   23,
       23,   25,   23,   23,   23,   23,   23,   26,   23,   23,
        1,    1,    1,    1,   23,    1,   27,   28,   29,   30,

       31,   32,   33,   34,   35,   23,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   52,    1,   53,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[54] =
    {   0,
        1,    1,    2,    3,    1,    1,    4,    4,    5,    1,
        6,    6,    6,    6,    6,    6,    7,    7,    7,    8,
        8,    9,    9,    9,    9,   10,    7,    7,    7,    7,
        8,    8,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,   10,    9,
        9,    1,    1
    } ;

static yyconst flex_int16_t yy_base[562] =
    {   0,
        0,    0,   52,   56,   60,   63,   66,   69,  121,  135,
      150,  203,   71,   73,  256,  309,  362,  415,  468,  521,
      574,  627,  680,  733,   76,   81, 1058, 1059,   86,   89,
     1052,   64,   89, 1046,   60,  158,    0, 1038,    0,   79,
       89,   83,  141,  146,   96,  103,  150, 1009, 1014, 1021,
       63,  152,   41,   75,  101,   99,  191,  153, 1024,  147,
      157, 1059,  197,  221, 1045, 1059,  224,  236, 1059, 1059,
     1059, 1059, 1059, 1059,  239, 1059, 1059, 1059, 1059, 1059,
     1059, 1059, 1059, 1059,    0,    0, 1059, 1059,  242,  245,
        0, 1059,  248,  271,    0, 1059,  274,  277,    0, 1059,

      280,  283,    0, 1059,  286,  289,    0, 1059,  292,  295,
      160,  298, 1044, 1059, 1017,  193,  294, 1008,  316,    0,
      323,  331,    0,    0,    0,    0, 1029,    0, 1028,  236,
     1014,  300, 1014, 1015, 1010,  992, 1004,  319, 1001,    0,
      350,  992,  991,  994, 1007,    0,  198, 1006,  995,  991,
      999,  351,  998,  989,  996,  977,  311,  988,  311,  985,
      992,  977,  977,  985,  975,  355,  972,  194,  976,  346,
      987,  984,  986,  352,  984,  357,  969,  968,  975,  966,
      981,  301, 1002, 1059,  397,  402,    0,    0,  405,    0,
      408,    0,  430,    0,  433,    0,  436,    0,  439,  315,

      974,  973,  353,  974,  363,  974,  972,  433,    0,  430,
        0,    0,    0,    0,  984,    0,  966,  972,  962,  953,
      956,    0,  951,  948,  905,  903,  892,  873,  875,  874,
      874,  435,  739,  755,  745,  737,  735,  742,  739,    0,
      729,  745,  744,  733,  742,    0,    0,    0,  737,  726,
        0,  739,  738,    0,  733,  723,  726,  720,  734,  732,
      725,  733,  723,  715,  731,  722,  711,  712,  439,  715,
        0,  709,  719,  717,  711,  700,  695,  698,  683,  687,
      691,  422,  695,  455,  689,  691,  691,  686,  689,  689,
      681,  686,  299, 1059,    0,  689,  665,  669,    0,  683,

        0,    0,  669,  684,    0,  667,  675,    0,  677,    0,
      334,  685,  656,  668,    0,  673,  657,    0,  657,  658,
      446,  657,    0,  672,  659,  662,  635,    0,  637,    0,
      633,  644,  636,  630,  645,    0,  640,  626,  626,  638,
        0,  638,    0,  471,  644,  636,    0,  633,  624,  618,
        0,  634,    0,  629,    0,  622,  626,  626,  621,  624,
      624,  614, 1059, 1059,  620,  619,  619,  603,  616,  486,
      482,    0,  603,  606,    0,    0,  602,  617,    0,  582,
        0,  602,  605,    0,  591,    0,  578,  575,  592,  587,
        0,  573,  589,    0,  571,    0,  575,  578,  569,  584,

      579,  580,  578,  567,  579,    0,  574,    0,  582,  585,
      567,  556,  565,  558,  553,  559,    0, 1059, 1059,  564,
      563,  563,  562, 1059, 1059,  560,  561, 1059,    0,  540,
      540,  529,    0,  551,    0,  538,  536,  526,  524,  525,
      532,    0,  535,  517,  515,    0,  515,  519,  526,  528,
      512,  526,    0,  535,    0,  515,    0,  509,  523,  514,
      521, 1059, 1059,  515, 1059, 1059,  515,  502,    0,    0,
        0,    0,  500,  515,    0,  512,    0,  503,    0,  490,
      503,  509,    0,  484,    0,  481,    0,    0,  471,  473,
      475,  469, 1059, 1059,  472,  480,  483,  482,  467,    0,

        0,  476,  479,  474,  473,  462,  453,  455,  447,  420,
      429,  416,  417,    0,  409,    0,    0,  374,  346,    0,
      341,    0,  319,  152,   98,    0,   72,    0,    0,    0,
        0,    0,    0, 1059,  786,  796,  806,  816,  826,  836,
      846,  856,  866,  876,  886,  896,  906,  912,  917,  927,
      932,  942,  947,  952,  957,  962,  967,  977,  982,  985,
      990
    } ;

static yyconst flex_int16_t yy_def[562] =
    {   0,
      534,    1,  535,  535,  536,  536,  537,  537,  538,  538,
      539,  539,  540,  540,  541,  541,  542,  542,  543,  543,
      544,  544,  545,  545,  546,  546,  534,  534,  534,  534,
      547,  534,  534,  534,  548,  534,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  534,  534,  534,  550,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  551,  552,  534,  534,  534,  534,
      553,  534,  534,  534,  554,  534,  534,  534,  555,  534,

      534,  534,  556,  534,  534,  534,  557,  534,  534,  534,
      534,  534,  547,  534,  534,  534,  534,  534,  534,  558,
      534,  534,  559,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  534,  550,  534,  534,  534,  551,  552,  534,  553,
      534,  554,  534,  555,  534,  556,  534,  557,  534,  534,

      534,  534,  534,  534,  534,  534,  534,  534,  558,  560,
      559,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  561,  534,  549,  549,  549,  549,  549,  549,

      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      561,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,

      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  534,  534,  534,  534,  534,  534,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  534,  534,  549,  549,  549,  549,  549,  549,

      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,    0,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534
    } ;

static yyconst flex_int16_t yy_nxt[1113] =
    {   0,
       28,   29,   30,   29,   31,   32,   28,   33,   28,   34,
       35,   36,   36,   36,   36,   36,   37,   38,   39,   39,
       39,   40,   39,   39,   41,   39,   42,   43,   44,   45,
       46,   47,   48,   39,   49,   50,   51,   52,   53,   54,
       55,   39,   56,   57,   58,   39,   59,   60,   39,   39,
       61,   28,   28,   63,   64,   63,   65,   63,   64,   63,
       65,   67,   68,   67,   67,   68,   67,   71,  121,   71,
       71,  159,   71,   87,   87,   87,   87,  109,  110,  109,
      160,  111,  109,  110,  109,  123,  111,  112,  112,  112,
      112,  112,  112,  115,  116,  126,  127,  154,  117,  119,

      119,  119,  119,  119,  119,  128,  129,  155,  123,  118,
      130,   69,  131,  161,   69,  162,  533,   72,   73,  132,
       72,   73,   75,   75,   75,  165,  141,  163,  532,  166,
      142,   76,   77,   78,   79,   80,   75,   75,   75,  143,
      144,  145,  167,  164,  146,   76,   77,   78,   79,   80,
       81,   82,   83,   84,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,  121,  133,  122,  122,
      122,  122,  122,  122,  136,  134,  147,  135,  156,  174,
      148,  178,  137,  175,  149,  138,  157,  180,  181,  179,
      200,  139,  150,  140,  201,  176,  531,  158,  182,  182,

      182,   81,   81,   81,   82,   83,   84,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,  168,
      263,  169,  182,  182,  182,  185,  185,  185,  264,  203,
      170,  204,  235,  171,  236,  172,  173,  185,  185,  185,
      186,  186,  186,  189,  189,  189,  189,  189,  189,  191,
      191,  191,  214,  215,   81,   81,   88,   89,   90,   89,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,  191,  191,  191,  193,  193,  193,  193,  193,
      193,  195,  195,  195,  195,  195,  195,  197,  197,  197,
      197,  197,  197,  199,  199,  199,  199,  199,  199,  112,

      112,  112,  182,  182,  182,  370,  370,   88,   88,   88,
       89,   90,   89,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,  205,  208,  208,  208,  208,
      208,  208,  206,  210,  210,  210,  210,  210,  210,  121,
      217,  122,  122,  122,  122,  122,  122,  218,  224,  248,
      381,  282,  251,  283,  530,  225,  226,  252,  382,  249,
       88,   88,   92,   93,   94,   93,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,  228,  241,
      242,  259,  266,  275,  272,  529,  260,  286,  267,  528,
      229,  268,  289,  230,  273,  261,  287,  243,  185,  185,

      185,  290,  276,  186,  186,  186,  189,  189,  189,  191,
      191,  191,  527,   92,   92,   92,   93,   94,   93,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,  193,  193,  193,  195,  195,  195,  197,  197,  197,
      199,  199,  199,  208,  208,  208,  208,  208,  208,  293,
      294,  310,  526,  525,  524,  343,  357,  523,  311,  312,
      293,  294,  344,  345,  522,  358,   92,   92,   96,   97,
       98,   97,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,  360,  521,  390,  408,  534,  534,
      520,  519,  518,  361,  391,  409,  371,  371,  371,  371,

      371,  371,  294,  517,  516,  515,  514,  513,  512,  511,
      510,  509,  508,  294,  507,  506,  505,  504,  503,   96,
       96,   96,   97,   98,   97,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,  502,  501,  500,
      499,  498,  497,  496,  495,  494,  493,  492,  491,  490,
      489,  488,  487,  486,  485,  484,  483,  482,  481,  480,
      479,  478,  477,  476,  475,  474,  473,  472,  471,  470,
      469,  468,   96,   96,  100,  101,  102,  101,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      467,  466,  465,  464,  463,  462,  461,  460,  459,  458,

      457,  456,  455,  454,  453,  452,  451,  450,  449,  448,
      447,  446,  445,  444,  443,  442,  441,  440,  439,  438,
      437,  436,  435,  434,  433,  100,  100,  100,  101,  102,
      101,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  432,  431,  430,  429,  428,  427,  426,
      425,  424,  423,  422,  421,  420,  419,  418,  417,  416,
      415,  414,  413,  412,  411,  410,  407,  406,  405,  404,
      403,  402,  401,  400,  399,  398,  397,  396,  100,  100,
      104,  105,  106,  105,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  395,  394,  393,  392,

      389,  388,  387,  386,  385,  384,  383,  380,  379,  378,
      377,  376,  375,  374,  373,  372,  369,  368,  367,  366,
      365,  364,  363,  362,  359,  356,  355,  354,  353,  352,
      351,  104,  104,  104,  105,  106,  105,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  350,
      349,  348,  347,  346,  342,  341,  340,  339,  338,  337,
      336,  335,  334,  333,  332,  331,  330,  329,  328,  327,
      326,  325,  324,  323,  322,  321,  320,  319,  318,  317,
      316,  315,  314,  313,  104,  104,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   66,   66,   66,   66,

       66,   66,   66,   66,   66,   66,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  108,  108,  108,  108,

      108,  108,  108,  108,  108,  108,  113,  309,  113,  113,
      113,  113,  113,  113,  113,  113,  122,  122,  308,  307,
      306,  122,  124,  124,  124,  124,  124,  183,  305,  183,
      183,  183,  183,  183,  183,  183,  183,  187,  187,  187,
      187,  187,  188,  304,  303,  188,  188,  188,  188,  188,
      188,  188,  190,  190,  190,  190,  190,  192,  192,  192,
      192,  192,  194,  194,  194,  194,  194,  196,  196,  196,
      196,  196,  198,  198,  198,  198,  198,  209,  302,  209,
      209,  209,  209,  209,  209,  209,  209,  211,  211,  211,
      210,  301,  210,  371,  300,  371,  299,  298,  297,  296,

      295,  292,  291,  288,  285,  284,  184,  281,  280,  279,
      278,  277,  274,  271,  270,  269,  265,  262,  258,  257,
      256,  255,  254,  253,  250,  247,  246,  245,  244,  240,
      239,  238,  237,  234,  233,  232,  231,  227,  223,  222,
      221,  220,  219,  216,  213,  212,  207,  202,  114,  184,
      177,  153,  152,  151,  125,  120,  114,  534,   27,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,

      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534
    } ;

static yyconst flex_int16_t yy_chk[1113] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    4,    4,    4,
        4,    5,    5,    5,    6,    6,    6,    7,   35,    7,
        8,   53,    8,   13,   13,   14,   14,   25,   25,   25,
       53,   25,   26,   26,   26,   35,   26,   29,   29,   29,
       30,   30,   30,   32,   32,   40,   40,   51,   32,   33,

       33,   33,   33,   33,   33,   41,   41,   51,   35,   32,
       41,    5,   42,   54,    6,   54,  527,    7,    7,   42,
        8,    8,    9,    9,    9,   56,   45,   55,  525,   56,
       45,    9,    9,    9,    9,    9,   10,   10,   10,   45,
       46,   46,   56,   55,   46,   10,   10,   10,   10,   10,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   36,   43,   36,   36,
       36,   36,   36,   36,   44,   43,   47,   43,   52,   58,
       47,   60,   44,   58,   47,   44,   52,   61,   61,   60,
      111,   44,   47,   44,  111,   58,  524,   52,   63,   63,

       63,   11,   11,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   57,
      168,   57,   64,   64,   64,   67,   67,   67,  168,  116,
       57,  116,  147,   57,  147,   57,   57,   68,   68,   68,
       75,   75,   75,   89,   89,   89,   90,   90,   90,   93,
       93,   93,  130,  130,   12,   12,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   94,   94,   94,   97,   97,   97,   98,   98,
       98,  101,  101,  101,  102,  102,  102,  105,  105,  105,
      106,  106,  106,  109,  109,  109,  110,  110,  110,  112,

      112,  112,  182,  182,  182,  293,  293,   15,   15,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,  117,  119,  119,  119,  119,
      119,  119,  117,  121,  121,  121,  121,  121,  121,  122,
      132,  122,  122,  122,  122,  122,  122,  132,  138,  157,
      311,  200,  159,  200,  523,  138,  138,  159,  311,  157,
       16,   16,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,  141,  152,
      152,  166,  170,  176,  174,  521,  166,  203,  170,  519,
      141,  170,  205,  141,  174,  166,  203,  152,  185,  185,

      185,  205,  176,  186,  186,  186,  189,  189,  189,  191,
      191,  191,  518,   17,   17,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,  193,  193,  193,  195,  195,  195,  197,  197,  197,
      199,  199,  199,  208,  208,  208,  208,  208,  208,  210,
      210,  232,  515,  513,  512,  269,  282,  511,  232,  232,
      210,  210,  269,  269,  510,  282,   18,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,  284,  509,  321,  344,  371,  371,
      508,  507,  506,  284,  321,  344,  370,  370,  370,  370,

      370,  370,  371,  505,  504,  503,  502,  499,  498,  497,
      496,  495,  492,  371,  491,  490,  489,  486,  484,   19,
       19,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,  482,  481,  480,
      478,  476,  474,  473,  468,  467,  464,  461,  460,  459,
      458,  456,  454,  452,  451,  450,  449,  448,  447,  445,
      444,  443,  441,  440,  439,  438,  437,  436,  434,  432,
      431,  430,   20,   20,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
      427,  426,  423,  422,  421,  420,  416,  415,  414,  413,

      412,  411,  410,  409,  407,  405,  404,  403,  402,  401,
      400,  399,  398,  397,  395,  393,  392,  390,  389,  388,
      387,  385,  383,  382,  380,   21,   21,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,  378,  377,  374,  373,  369,  368,  367,
      366,  365,  362,  361,  360,  359,  358,  357,  356,  354,
      352,  350,  349,  348,  346,  345,  342,  340,  339,  338,
      337,  335,  334,  333,  332,  331,  329,  327,   22,   22,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,  326,  325,  324,  322,

      320,  319,  317,  316,  314,  313,  312,  309,  307,  306,
      304,  303,  300,  298,  297,  296,  292,  291,  290,  289,
      288,  287,  286,  285,  283,  281,  280,  279,  278,  277,
      276,   23,   23,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,  275,
      274,  273,  272,  270,  268,  267,  266,  265,  264,  263,
      262,  261,  260,  259,  258,  257,  256,  255,  253,  252,
      250,  249,  245,  244,  243,  242,  241,  239,  238,  237,
      236,  235,  234,  233,   24,   24,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  536,  536,  536,  536,

      536,  536,  536,  536,  536,  536,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  541,  541,  541,  541,
      541,  541,  541,  541,  541,  541,  542,  542,  542,  542,
      542,  542,  542,  542,  542,  542,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  544,  544,  544,  544,
      544,  544,  544,  544,  544,  544,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  545,  546,  546,  546,  546,

      546,  546,  546,  546,  546,  546,  547,  231,  547,  547,
      547,  547,  547,  547,  547,  547,  548,  548,  230,  229,
      228,  548,  549,  549,  549,  549,  549,  550,  227,  550,
      550,  550,  550,  550,  550,  550,  550,  551,  551,  551,
      551,  551,  552,  226,  225,  552,  552,  552,  552,  552,
      552,  552,  553,  553,  553,  553,  553,  554,  554,  554,
      554,  554,  555,  555,  555,  555,  555,  556,  556,  556,
      556,  556,  557,  557,  557,  557,  557,  558,  224,  558,
      558,  558,  558,  558,  558,  558,  558,  559,  559,  559,
      560,  223,  560,  561,  221,  561,  220,  219,  218,  217,

      215,  207,  206,  204,  202,  201,  183,  181,  180,  179,
      178,  177,  175,  173,  172,  171,  169,  167,  165,  164,
      163,  162,  161,  160,  158,  156,  155,  154,  153,  151,
      150,  149,  148,  145,  144,  143,  142,  139,  137,  136,
      135,  134,  133,  131,  129,  127,  118,  115,  113,   65,
       59,   50,   49,   48,   38,   34,   31,   27,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,

      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[163] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 
    0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 
    0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 
    0, 0, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#include "BsParserFX.h"

#define YY_USER_ACTION yylloc->first_column = yycolumn + 1; yylloc->first_line = yylineno + 1; yycolumn += (int)yyleng; yylloc->filename = getCurrentFilename(yyextra);
#define YY_USER_INIT yylineno = 0; yycolumn = 0;
#define YY_NO_UNISTD_H 1
/* Start conditions */

#define INITIAL 0
#define INCLUDE 1
#define CODEBLOCK_HEADER 2
#define CODEBLOCK 3
#define CODEBLOCK_END 4
#define DEFINE_COND 5
#define DEFINE_COND_EXPR 6
#define UNDEF_COND 7
#define CONDITIONAL_IF 8
#define CONDITIONAL_IFDEF 9
#define CONDITIONAL_IFNDEF 10
#define CONDITIONAL_ELIF 11
#define CONDITIONAL_IGNORE 12

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#define YY_EXTRA_TYPE struct tagParseState *

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    yy_size_t yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (yyscan_t yyscanner );

int yyget_debug (yyscan_t yyscanner );

void yyset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra (yyscan_t yyscanner );

void yyset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *yyget_in (yyscan_t yyscanner );

void yyset_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *yyget_out (yyscan_t yyscanner );

void yyset_out  (FILE * out_str ,yyscan_t yyscanner );

yy_size_t yyget_leng (yyscan_t yyscanner );

char *yyget_text (yyscan_t yyscanner );

int yyget_lineno (yyscan_t yyscanner );

void yyset_lineno (int line_number ,yyscan_t yyscanner );

int yyget_column  (yyscan_t yyscanner );

void yyset_column (int column_no ,yyscan_t yyscanner );

YYSTYPE * yyget_lval (yyscan_t yyscanner );

void yyset_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

       YYLTYPE *yyget_lloc (yyscan_t yyscanner );
    
        void yyset_lloc (YYLTYPE * yylloc_param ,yyscan_t yyscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (yyscan_t yyscanner );
#else
extern int yywrap (yyscan_t yyscanner );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  ,yyscan_t yyscanner);
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param,YYLTYPE * yylloc_param ,yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		yy_load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 535 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 534 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
{ /* Skip blank */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
{ yylval->intValue = atoi(yytext); return TOKEN_INTEGER; }
	YY_BREAK
case 3:
YY_RULE_SETUP
{ yylval->intValue = (int)strtol(yytext, 0, 0); return TOKEN_INTEGER; }
	YY_BREAK
case 4:
YY_RULE_SETUP
{ yylval->floatValue = (float)atof(yytext); return TOKEN_FLOAT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
{ yylval->strValue = mmalloc_strdup(yyextra->memContext, yytext); return TOKEN_STRING; }
	YY_BREAK
case 6:
YY_RULE_SETUP
{ yylval->intValue = 1; return TOKEN_BOOLEAN; }
	YY_BREAK
case 7:
YY_RULE_SETUP
{ yylval->intValue = 0; return TOKEN_BOOLEAN; }
	YY_BREAK
/* Shader keywords */
case 8:
YY_RULE_SETUP
{ return TOKEN_OPTIONS; }
	YY_BREAK
case 9:
YY_RULE_SETUP
{ return TOKEN_TECHNIQUE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
{ return TOKEN_MIXIN; }
	YY_BREAK
/* Options keywords */
case 11:
YY_RULE_SETUP
{ return TOKEN_SEPARABLE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
{ return TOKEN_SORT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
{ return TOKEN_PRIORITY; }
	YY_BREAK
case 14:
YY_RULE_SETUP
{ return TOKEN_TRANSPARENT; }
	YY_BREAK
/* Technique keywords */
case 15:
YY_RULE_SETUP
{ return TOKEN_FEATURESET; }
	YY_BREAK
case 16:
YY_RULE_SETUP
{ return TOKEN_TAGS; }
	YY_BREAK
case 17:
YY_RULE_SETUP
{ return TOKEN_PASS; }
	YY_BREAK
case 18:
YY_RULE_SETUP
{ return TOKEN_VARIATIONS; }
	YY_BREAK
/* Pass keywords */
case 19:
YY_RULE_SETUP
{ return TOKEN_BLEND; }
	YY_BREAK
case 20:
YY_RULE_SETUP
{ return TOKEN_RASTER; }
	YY_BREAK
case 21:
YY_RULE_SETUP
{ return TOKEN_DEPTH; }
	YY_BREAK
case 22:
YY_RULE_SETUP
{ return TOKEN_STENCIL; }
	YY_BREAK
/* Variation keywords */
case 23:
YY_RULE_SETUP
{ return TOKEN_VARIATION; }
	YY_BREAK
/* Rasterizer state keywords */
case 24:
YY_RULE_SETUP
{ return TOKEN_FILLMODE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
{ return TOKEN_CULLMODE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
{ return TOKEN_SCISSOR; }
	YY_BREAK
case 27:
YY_RULE_SETUP
{ return TOKEN_MULTISAMPLE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
{ return TOKEN_AALINE; }
	YY_BREAK
/* Depth state keywords */
case 29:
YY_RULE_SETUP
{ return TOKEN_DEPTHREAD; }
	YY_BREAK
case 30:
YY_RULE_SETUP
{ return TOKEN_DEPTHWRITE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
{ return TOKEN_COMPAREFUNC; }
	YY_BREAK
case 32:
YY_RULE_SETUP
{ return TOKEN_DEPTHBIAS; }
	YY_BREAK
case 33:
YY_RULE_SETUP
{ return TOKEN_SDEPTHBIAS; }
	YY_BREAK
case 34:
YY_RULE_SETUP
{ return TOKEN_DEPTHCLIP; }
	YY_BREAK
/* Stencil state keywords */
case 35:
YY_RULE_SETUP
{ return TOKEN_STENCILREF; }
	YY_BREAK
case 36:
YY_RULE_SETUP
{ return TOKEN_ENABLED; }
	YY_BREAK
case 37:
YY_RULE_SETUP
{ return TOKEN_READMASK; }
	YY_BREAK
case 38:
YY_RULE_SETUP
{ return TOKEN_WRITEMASK; }
	YY_BREAK
case 39:
YY_RULE_SETUP
{ return TOKEN_STENCILOPFRONT; }
	YY_BREAK
case 40:
YY_RULE_SETUP
{ return TOKEN_STENCILOPBACK; }
	YY_BREAK
case 41:
YY_RULE_SETUP
{ return TOKEN_FAIL; }
	YY_BREAK
case 42:
YY_RULE_SETUP
{ return TOKEN_ZFAIL; }
	YY_BREAK
/* Blend state keywords */
case 43:
YY_RULE_SETUP
{ return TOKEN_ALPHATOCOVERAGE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
{ return TOKEN_INDEPENDANTBLEND; }
	YY_BREAK
case 45:
YY_RULE_SETUP
{ return TOKEN_TARGET; }
	YY_BREAK
case 46:
YY_RULE_SETUP
{ return TOKEN_INDEX; }
	YY_BREAK
case 47:
YY_RULE_SETUP
{ return TOKEN_COLOR; }
	YY_BREAK
case 48:
YY_RULE_SETUP
{ return TOKEN_ALPHA; }
	YY_BREAK
case 49:
YY_RULE_SETUP
{ return TOKEN_SOURCE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
{ return TOKEN_DEST; }
	YY_BREAK
case 51:
YY_RULE_SETUP
{ return TOKEN_OP; }
	YY_BREAK
/* State values */
case 52:
YY_RULE_SETUP
{ yylval->intValue = FMV_Wire; return TOKEN_FILLMODEVALUE; }
	YY_BREAK
case 53:
YY_RULE_SETUP
{ yylval->intValue = FMV_Solid; return TOKEN_FILLMODEVALUE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
{ yylval->intValue = CASV_None; return TOKEN_CULLANDQUEUEVALUE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
{ yylval->intValue = CASV_CW; return TOKEN_CULLANDQUEUEVALUE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
{ yylval->intValue = CASV_CCW; return TOKEN_CULLANDQUEUEVALUE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
{ yylval->intValue = CASV_FrontToBack; return TOKEN_CULLANDQUEUEVALUE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
{ yylval->intValue = CASV_BackToFront; return TOKEN_CULLANDQUEUEVALUE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
{ yylval->intValue = CFV_Fail; return TOKEN_COMPFUNCVALUE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
{ yylval->intValue = CFV_Pass; return TOKEN_COMPFUNCVALUE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
{ yylval->intValue = CFV_LT; return TOKEN_COMPFUNCVALUE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
{ yylval->intValue = CFV_LTE; return TOKEN_COMPFUNCVALUE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
{ yylval->intValue = CFV_EQ; return TOKEN_COMPFUNCVALUE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
{ yylval->intValue = CFV_NEQ; return TOKEN_COMPFUNCVALUE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
{ yylval->intValue = CFV_GTE; return TOKEN_COMPFUNCVALUE; }
	YY_BREAK
case 66:
YY_RULE_SETUP
{ yylval->intValue = CFV_GT; return TOKEN_COMPFUNCVALUE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
{ yylval->intValue = OV_Keep; return TOKEN_OPVALUE; }
	YY_BREAK
case 68:
YY_RULE_SETUP
{ yylval->intValue = OV_Zero; return TOKEN_OPVALUE; }
	YY_BREAK
case 69:
YY_RULE_SETUP
{ yylval->intValue = OV_Replace; return TOKEN_OPVALUE; }
	YY_BREAK
case 70:
YY_RULE_SETUP
{ yylval->intValue = OV_Incr; return TOKEN_OPVALUE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
{ yylval->intValue = OV_Decr; return TOKEN_OPVALUE; }
	YY_BREAK
case 72:
YY_RULE_SETUP
{ yylval->intValue = OV_IncrWrap; return TOKEN_OPVALUE; }
	YY_BREAK
case 73:
YY_RULE_SETUP
{ yylval->intValue = OV_DecrWrap; return TOKEN_OPVALUE; }
	YY_BREAK
case 74:
YY_RULE_SETUP
{ yylval->intValue = OV_Invert; return TOKEN_OPVALUE; }
	YY_BREAK
case 75:
YY_RULE_SETUP
{ yylval->intValue = OV_One; return TOKEN_OPVALUE; }
	YY_BREAK
case 76:
YY_RULE_SETUP
{ yylval->intValue = OV_DestColor; return TOKEN_OPVALUE; }
	YY_BREAK
case 77:
YY_RULE_SETUP
{ yylval->intValue = OV_SrcColor; return TOKEN_OPVALUE; }
	YY_BREAK
case 78:
YY_RULE_SETUP
{ yylval->intValue = OV_InvDestColor; return TOKEN_OPVALUE; }
	YY_BREAK
case 79:
YY_RULE_SETUP
{ yylval->intValue = OV_InvSrcColor; return TOKEN_OPVALUE; }
	YY_BREAK
case 80:
YY_RULE_SETUP
{ yylval->intValue = OV_DestAlpha; return TOKEN_OPVALUE; }
	YY_BREAK
case 81:
YY_RULE_SETUP
{ yylval->intValue = OV_SrcAlpha; return TOKEN_OPVALUE; }
	YY_BREAK
case 82:
YY_RULE_SETUP
{ yylval->intValue = OV_InvDestAlpha; return TOKEN_OPVALUE; }
	YY_BREAK
case 83:
YY_RULE_SETUP
{ yylval->intValue = OV_InvSrcAlpha; return TOKEN_OPVALUE; }
	YY_BREAK
case 84:
YY_RULE_SETUP
{ yylval->intValue = BOV_Add; return TOKEN_BLENDOPVALUE; }
	YY_BREAK
case 85:
YY_RULE_SETUP
{ yylval->intValue = BOV_Subtract; return TOKEN_BLENDOPVALUE; }
	YY_BREAK
case 86:
YY_RULE_SETUP
{ yylval->intValue = BOV_RevSubtract; return TOKEN_BLENDOPVALUE; }
	YY_BREAK
case 87:
YY_RULE_SETUP
{ yylval->intValue = BOV_Min; return TOKEN_BLENDOPVALUE; }
	YY_BREAK
case 88:
YY_RULE_SETUP
{ yylval->intValue = BOV_Max; return TOKEN_BLENDOPVALUE; }
	YY_BREAK
case 89:
YY_RULE_SETUP
{ yylval->intValue = 0x0; return TOKEN_COLORMASK; }
	YY_BREAK
case 90:
YY_RULE_SETUP
{ yylval->intValue = 0x1; return TOKEN_COLORMASK; }
	YY_BREAK
case 91:
YY_RULE_SETUP
{ yylval->intValue = 0x2; return TOKEN_COLORMASK; }
	YY_BREAK
case 92:
YY_RULE_SETUP
{ yylval->intValue = 0x4; return TOKEN_COLORMASK; }
	YY_BREAK
case 93:
YY_RULE_SETUP
{ yylval->intValue = 0x8; return TOKEN_COLORMASK; }
	YY_BREAK
case 94:
YY_RULE_SETUP
{ yylval->intValue = 0x3; return TOKEN_COLORMASK; }
	YY_BREAK
case 95:
YY_RULE_SETUP
{ yylval->intValue = 0x5; return TOKEN_COLORMASK; }
	YY_BREAK
case 96:
YY_RULE_SETUP
{ yylval->intValue = 0x9; return TOKEN_COLORMASK; }
	YY_BREAK
case 97:
YY_RULE_SETUP
{ yylval->intValue = 0x6; return TOKEN_COLORMASK; }
	YY_BREAK
case 98:
YY_RULE_SETUP
{ yylval->intValue = 0xA; return TOKEN_COLORMASK; }
	YY_BREAK
case 99:
YY_RULE_SETUP
{ yylval->intValue = 0xC; return TOKEN_COLORMASK; }
	YY_BREAK
case 100:
YY_RULE_SETUP
{ yylval->intValue = 0x7; return TOKEN_COLORMASK; }
	YY_BREAK
case 101:
YY_RULE_SETUP
{ yylval->intValue = 0xB; return TOKEN_COLORMASK; }
	YY_BREAK
case 102:
YY_RULE_SETUP
{ yylval->intValue = 0xD; return TOKEN_COLORMASK; }
	YY_BREAK
case 103:
YY_RULE_SETUP
{ yylval->intValue = 0xE; return TOKEN_COLORMASK; }
	YY_BREAK
case 104:
YY_RULE_SETUP
{ yylval->intValue = 0xF; return TOKEN_COLORMASK; }
	YY_BREAK
/* Preprocessor */
case 105:
YY_RULE_SETUP
{ BEGIN(INCLUDE); }
	YY_BREAK
case 106:
/* rule 106 can match eol */
YY_RULE_SETUP
{ /* Skip blank */ }
	YY_BREAK
case 107:
YY_RULE_SETUP
{
	int size = 0;
	char* includeBuffer = includePush(yyextra, yytext, yylineno, yycolumn, &size);
	if(!includeBuffer)
		yyterminate();

	YY_BUFFER_STATE currentBuffer = YY_CURRENT_BUFFER;
	YY_BUFFER_STATE newBuffer = yy_scan_buffer(includeBuffer,size,yyscanner);

	yy_switch_to_buffer(currentBuffer,yyscanner);
	yypush_buffer_state(newBuffer,yyscanner);

	yylineno = 0; 
	yycolumn = 0;

	BEGIN(INITIAL);
	}
	YY_BREAK
case 108:
YY_RULE_SETUP
{ return yytext[0]; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(INCLUDE):
case YY_STATE_EOF(CODEBLOCK_HEADER):
case YY_STATE_EOF(CODEBLOCK):
case YY_STATE_EOF(CODEBLOCK_END):
case YY_STATE_EOF(DEFINE_COND):
case YY_STATE_EOF(DEFINE_COND_EXPR):
case YY_STATE_EOF(UNDEF_COND):
case YY_STATE_EOF(CONDITIONAL_IF):
case YY_STATE_EOF(CONDITIONAL_IFDEF):
case YY_STATE_EOF(CONDITIONAL_IFNDEF):
case YY_STATE_EOF(CONDITIONAL_ELIF):
case YY_STATE_EOF(CONDITIONAL_IGNORE):
{
	if(!yyextra->includeStack)
		yyterminate();

	yypop_buffer_state(yyscanner);
	includePop(yyextra);
}
	YY_BREAK
case 109:
YY_RULE_SETUP
{ BEGIN(DEFINE_COND); }
	YY_BREAK
case 110:
YY_RULE_SETUP
{ /* Skip blank */ }
	YY_BREAK
case 111:
YY_RULE_SETUP
{ addDefine(yyextra, yytext); BEGIN(DEFINE_COND_EXPR); }
	YY_BREAK
case 112:
/* rule 112 can match eol */
YY_RULE_SETUP
{ BEGIN(INITIAL); }
	YY_BREAK
case 113:
YY_RULE_SETUP
{ return yytext[0]; }
	YY_BREAK
case 114:
YY_RULE_SETUP
{ addDefineExpr(yyextra, yytext); BEGIN(INITIAL); }
	YY_BREAK
case 115:
/* rule 115 can match eol */
YY_RULE_SETUP
{ BEGIN(INITIAL); }
	YY_BREAK
case 116:
YY_RULE_SETUP
{ BEGIN(UNDEF_COND); }
	YY_BREAK
case 117:
/* rule 117 can match eol */
YY_RULE_SETUP
{ /* Skip blank */ }
	YY_BREAK
case 118:
YY_RULE_SETUP
{ removeDefine(yyextra, yytext); BEGIN(INITIAL); }
	YY_BREAK
case 119:
YY_RULE_SETUP
{ return yytext[0]; }
	YY_BREAK
case 120:
YY_RULE_SETUP
{ BEGIN(CONDITIONAL_IF); }
	YY_BREAK
case 121:
/* rule 121 can match eol */
YY_RULE_SETUP
{ /* Skip blank */ }
	YY_BREAK
case 122:
YY_RULE_SETUP
{ 
	int isEnabled = pushConditional(yyextra, isDefineEnabled(yyextra, yytext));
	if(!isEnabled)
		BEGIN(CONDITIONAL_IGNORE);
	else
		BEGIN(INITIAL);
}
	YY_BREAK
case 123:
YY_RULE_SETUP

	YY_BREAK
case 124:
YY_RULE_SETUP
{ BEGIN(CONDITIONAL_IFDEF); }
	YY_BREAK
case 125:
/* rule 125 can match eol */
YY_RULE_SETUP
{ /* Skip blank */ }
	YY_BREAK
case 126:
YY_RULE_SETUP
{ 
	int isEnabled = pushConditional(yyextra, hasDefine(yyextra, yytext));
	if(!isEnabled)
		BEGIN(CONDITIONAL_IGNORE);
	else
		BEGIN(INITIAL);
}
	YY_BREAK
case 127:
YY_RULE_SETUP
{ return yytext[0]; }
	YY_BREAK
case 128:
YY_RULE_SETUP
{ BEGIN(CONDITIONAL_IFNDEF); }
	YY_BREAK
case 129:
/* rule 129 can match eol */
YY_RULE_SETUP
{ /* Skip blank */ }
	YY_BREAK
case 130:
YY_RULE_SETUP
{ 
	int isEnabled = pushConditional(yyextra, !hasDefine(yyextra, yytext));
	if(!isEnabled)
		BEGIN(CONDITIONAL_IGNORE);
	else
		BEGIN(INITIAL);
}
	YY_BREAK
case 131:
YY_RULE_SETUP
{ return yytext[0]; }
	YY_BREAK
case 132:
YY_RULE_SETUP
{ 
	if(!switchConditional(yyextra))
		BEGIN(CONDITIONAL_IGNORE); 
}
	YY_BREAK
case 133:
YY_RULE_SETUP
{ BEGIN(CONDITIONAL_IGNORE); }
	YY_BREAK
case 134:
YY_RULE_SETUP
{ popConditional(yyextra); }
	YY_BREAK
case 135:
/* rule 135 can match eol */
YY_RULE_SETUP
{ /* Skip */ }
	YY_BREAK
case 136:
YY_RULE_SETUP
{ pushConditional(yyextra, 0); }
	YY_BREAK
case 137:
YY_RULE_SETUP
{ pushConditional(yyextra, 0); }
	YY_BREAK
case 138:
YY_RULE_SETUP
{ pushConditional(yyextra, 0); }
	YY_BREAK
case 139:
YY_RULE_SETUP
{ 
	if(switchConditional(yyextra))
		BEGIN(INITIAL);
}
	YY_BREAK
case 140:
YY_RULE_SETUP
{ BEGIN(CONDITIONAL_ELIF); }
	YY_BREAK
case 141:
YY_RULE_SETUP
{ 
	if(popConditional(yyextra))
		BEGIN(INITIAL);
}
	YY_BREAK
case 142:
YY_RULE_SETUP
{ /* Skip */ }
	YY_BREAK
case 143:
/* rule 143 can match eol */
YY_RULE_SETUP
{ /* Skip blank */ }
	YY_BREAK
case 144:
YY_RULE_SETUP
{ 
	int isEnabled = setConditional(yyextra, hasDefine(yyextra, yytext));
	if(!isEnabled)
		BEGIN(CONDITIONAL_IGNORE);
	else
		BEGIN(INITIAL);
}
	YY_BREAK
case 145:
YY_RULE_SETUP
{ return yytext[0]; }
	YY_BREAK
/* Code block */
case 146:
YY_RULE_SETUP
{ BEGIN(CODEBLOCK_HEADER); return TOKEN_CODE; }
	YY_BREAK
/* Track when the code block begins, insert all code block characters into our own buffer, record a sequential index */
/* of all code blocks in the text, and track bracket open/closed state so we know when we're done with the code block. */
/* And finally output a sequential code block index to the parser (it shouldn't be aware of anything else in the block). */
case 147:
YY_RULE_SETUP
{ BEGIN(CODEBLOCK); beginCodeBlock(yyextra); yyextra->numOpenBrackets = 1; return yytext[0]; }
	YY_BREAK
case 148:
/* rule 148 can match eol */
YY_RULE_SETUP
{ /* Skip blank */ }
	YY_BREAK
case 149:
YY_RULE_SETUP
{ return yytext[0]; }
	YY_BREAK
case 150:
YY_RULE_SETUP
{ yyextra->numOpenBrackets++; appendCodeBlock(yyextra, yytext, 1); }
	YY_BREAK
case 151:
YY_RULE_SETUP
{ 
	yyextra->numOpenBrackets--; 

	if(yyextra->numOpenBrackets == 0)
	{
		BEGIN(CODEBLOCK_END);
		unput('0');
	}
	else
		appendCodeBlock(yyextra, yytext, 1);
}
	YY_BREAK
case 152:
/* rule 152 can match eol */
YY_RULE_SETUP
{ appendCodeBlock(yyextra, yytext, 1); }
	YY_BREAK
/* Logic for manually inserting "Index = codeBlockIndex;". We insert arbitrary numbers which allows us to sequentially */
/* output all the tokens we need. We use only single-character values so we don't override anything in the text buffer */
/* (since the starting value was also a single character "{"). */
case 153:
YY_RULE_SETUP
{ unput('1'); return TOKEN_INDEX; }
	YY_BREAK
case 154:
YY_RULE_SETUP
{ unput('2'); return '='; }
	YY_BREAK
case 155:
YY_RULE_SETUP
{ yylval->intValue = getCodeBlockIndex(yyextra); unput('3'); return TOKEN_INTEGER; }
	YY_BREAK
case 156:
YY_RULE_SETUP
{ unput('4'); return ';'; }
	YY_BREAK
case 157:
YY_RULE_SETUP
{ BEGIN(INITIAL); return '}'; }
	YY_BREAK
case 158:
/* rule 158 can match eol */
YY_RULE_SETUP
{ /* Never reached */ }
	YY_BREAK
/* Catch all rules */
case 159:
YY_RULE_SETUP
{ }
	YY_BREAK
case 160:
YY_RULE_SETUP
{ yylval->strValue = mmalloc_strdup(yyextra->memContext, yytext); return TOKEN_IDENTIFIER; }
	YY_BREAK
case 161:
YY_RULE_SETUP
{ return yytext[0]; }
	YY_BREAK
case 162:
YY_RULE_SETUP
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 535 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 535 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 534);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp , yyscan_t yyscanner)
{
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = yyg->yy_n_chars + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	if ( c == '\n' )
		   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	yy_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf ,yyscanner );

	yyfree((void *) b ,yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void yyset_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *yyget_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void yyset_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int yylex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */

int yylex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    yyset_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

