set(BS_NULLAUDIO_INC_NOFILTER
	"BsNullAudioPrerequisites.h"
	"BsNullAudio.h"
)

set(BS_NULLAUDIO_SRC_NOFILTER
	"BsNullPlugin.cpp"
	"BsNullAudio.cpp"
)

if(WIN32)
	set(BS_NULLAUDIO_WIN32RES
	"BsNullWin32Resource.rc"
	)
else()
	set(BS_NULLAUDIO_WIN32RES )
endif()

source_group("" FILES ${BS_NULLAUDIO_INC_NOFILTER} ${BS_NULLAUDIO_SRC_NOFILTER} ${BS_NULLAUDIO_WIN32RES})

set(BS_NULLAUDIO_SRC
	${BS_NULLAUDIO_INC_NOFILTER}
	${BS_NULLAUDIO_SRC_NOFILTER}
	${BS_NULLAUDIO_WIN32RES}
)
